// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PwSites2;

namespace PwSites2.Migrations
{
    [DbContext(typeof(SiteContext))]
    partial class SiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("PwSites2.MapSiteToUidPw", b =>
                {
                    b.Property<int>("MapSiteToUidPwId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UidPwId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MapSiteToUidPwId");

                    b.ToTable("TblMapSiteToUidPws");
                });

            modelBuilder.Entity("PwSites2.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UidPwId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SiteId");

                    b.ToTable("TblSites");
                });

            modelBuilder.Entity("PwSites2.UidPw", b =>
                {
                    b.Property<int>("UidPwId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UidPwId");

                    b.ToTable("TblUidPws");
                });
#pragma warning restore 612, 618
        }
    }
}
