// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject2
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject2PackageString = "e0b58a89-2c52-4306-a78c-86a751264d71";
        public static Guid guidVSIXProject2Package = new Guid(guidVSIXProject2PackageString);

        public const string guidVSIXProject2PackageCmdSetString = "2bba23ea-42f4-4c53-9562-77850f6278e9";
        public static Guid guidVSIXProject2PackageCmdSet = new Guid(guidVSIXProject2PackageCmdSetString);

        public const string guidImagesString = "1cd82eb0-37d9-4d54-858e-f85db1cabed0";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}