//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCollection1.Properties {


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieCollection1.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap Blue_fullBg_noSideText {
			get {
				object obj = ResourceManager.GetObject("Blue_fullBg_noSideText", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_addCollection {
			get {
				object obj = ResourceManager.GetObject("button_addCollection", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_search_active {
			get {
				object obj = ResourceManager.GetObject("button_search_active", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_showDVD_L {
			get {
				object obj = ResourceManager.GetObject("button_showDVD_L", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_showDvd_r {
			get {
				object obj = ResourceManager.GetObject("button_showDvd_r", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_smallBlue_search {
			get {
				object obj = ResourceManager.GetObject("button_smallBlue_search", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap button_viewDvd_active {
			get {
				object obj = ResourceManager.GetObject("button_viewDvd_active", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Icon dvd_starter_kit {
			get {
				object obj = ResourceManager.GetObject("dvd_starter_kit", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		internal static System.Drawing.Bitmap icon_magnifyingGlass {
			get {
				object obj = ResourceManager.GetObject("icon_magnifyingGlass", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap panel_dvdInfo_noTxt {
			get {
				object obj = ResourceManager.GetObject("panel_dvdInfo_noTxt", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap PanelBG {
			get {
				object obj = ResourceManager.GetObject("PanelBG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap PanelBG_Tile {
			get {
				object obj = ResourceManager.GetObject("PanelBG_Tile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Record {
			get {
				object obj = ResourceManager.GetObject("Record", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap star_empty {
			get {
				object obj = ResourceManager.GetObject("star_empty", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap star_filled {
			get {
				object obj = ResourceManager.GetObject("star_filled", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
