#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class JasDb : System.Data.Linq.DataContext {

	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

	#region Extensibility Method Definitions
	partial void OnCreated();
	partial void InsertCoolPeople(CoolPeople instance);
	partial void UpdateCoolPeople(CoolPeople instance);
	partial void DeleteCoolPeople(CoolPeople instance);
	#endregion

	public JasDb(string connection) :
		base(connection, mappingSource) {
		OnCreated();
	}

	public JasDb(System.Data.IDbConnection connection) :
		base(connection, mappingSource) {
		OnCreated();
	}

	public JasDb(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
		base(connection, mappingSource) {
		OnCreated();
	}

	public JasDb(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
		base(connection, mappingSource) {
		OnCreated();
	}

	public System.Data.Linq.Table<CoolPeople> CoolPeople {
		get {
			return this.GetTable<CoolPeople>();
		}
	}
}

[Table()]
public partial class CoolPeople : INotifyPropertyChanging, INotifyPropertyChanged {

	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

	private string _LastName;

	private string _FirstName;

	private string _URL;

	#region Extensibility Method Definitions
	partial void OnLoaded();
	partial void OnValidate(System.Data.Linq.ChangeAction action);
	partial void OnCreated();
	partial void OnLastNameChanging(string value);
	partial void OnLastNameChanged();
	partial void OnFirstNameChanging(string value);
	partial void OnFirstNameChanged();
	partial void OnURLChanging(string value);
	partial void OnURLChanged();
	#endregion

	public CoolPeople() {
		OnCreated();
	}

	[Column(Storage = "_LastName", DbType = "NVarChar(40) NOT NULL", CanBeNull = false)]
	public string LastName {
		get {
			return this._LastName;
		}
		set {
			if ((this._LastName != value)) {
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}

	[Column(Storage = "_FirstName", DbType = "NVarChar(40)")]
	public string FirstName {
		get {
			return this._FirstName;
		}
		set {
			if ((this._FirstName != value)) {
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}

	[Column(Storage = "_URL", DbType = "NVarChar(256) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
	public string URL {
		get {
			return this._URL;
		}
		set {
			if ((this._URL != value)) {
				this.OnURLChanging(value);
				this.SendPropertyChanging();
				this._URL = value;
				this.SendPropertyChanged("URL");
				this.OnURLChanged();
			}
		}
	}

	public event PropertyChangingEventHandler PropertyChanging;

	public event PropertyChangedEventHandler PropertyChanged;

	protected virtual void SendPropertyChanging() {
		if ((this.PropertyChanging != null)) {
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}

	protected virtual void SendPropertyChanged(String propertyName) {
		if ((this.PropertyChanged != null)) {
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
