//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace TestAmazonWebServices_1.com.acrosscommunications.ws {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneSoap", Namespace="http://ws.acrosscommunications.com/")]
    public class Phone : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Phone() {
            this.Url = "http://ws.acrosscommunications.com/Phone.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/Call", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Call(string strGuidNotification, string strDialNumber) {
            this.Invoke("Call", new object[] {
                        strGuidNotification,
                        strDialNumber});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCall(string strGuidNotification, string strDialNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Call", new object[] {
                        strGuidNotification,
                        strDialNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCall(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/HangUp", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void HangUp(string strGuidNotification) {
            this.Invoke("HangUp", new object[] {
                        strGuidNotification});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHangUp(string strGuidNotification, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HangUp", new object[] {
                        strGuidNotification}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndHangUp(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/Say", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Say(string strGuidNotification, string strText) {
            this.Invoke("Say", new object[] {
                        strGuidNotification,
                        strText});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSay(string strGuidNotification, string strText, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Say", new object[] {
                        strGuidNotification,
                        strText}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSay(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/SayWithDigitEvent", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SayWithDigitEvent(string strGuidNotification, string strText, string strLastDigits, int MaxDigits) {
            object[] results = this.Invoke("SayWithDigitEvent", new object[] {
                        strGuidNotification,
                        strText,
                        strLastDigits,
                        MaxDigits});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSayWithDigitEvent(string strGuidNotification, string strText, string strLastDigits, int MaxDigits, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SayWithDigitEvent", new object[] {
                        strGuidNotification,
                        strText,
                        strLastDigits,
                        MaxDigits}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSayWithDigitEvent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/Prepare", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Prepare(string strGuidNotification, string PhoneNumber) {
            this.Invoke("Prepare", new object[] {
                        strGuidNotification,
                        PhoneNumber});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrepare(string strGuidNotification, string PhoneNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Prepare", new object[] {
                        strGuidNotification,
                        PhoneNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrepare(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/PlayFile", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PlayFile(string strGuidNotification, string strFile) {
            this.Invoke("PlayFile", new object[] {
                        strGuidNotification,
                        strFile});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPlayFile(string strGuidNotification, string strFile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PlayFile", new object[] {
                        strGuidNotification,
                        strFile}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPlayFile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/PlayFileWithDigitEvent", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PlayFileWithDigitEvent(string strGuidNotification, string strFile, string strLastDigits, int MaxDigits) {
            object[] results = this.Invoke("PlayFileWithDigitEvent", new object[] {
                        strGuidNotification,
                        strFile,
                        strLastDigits,
                        MaxDigits});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPlayFileWithDigitEvent(string strGuidNotification, string strFile, string strLastDigits, int MaxDigits, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PlayFileWithDigitEvent", new object[] {
                        strGuidNotification,
                        strFile,
                        strLastDigits,
                        MaxDigits}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndPlayFileWithDigitEvent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/PlayDigits", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PlayDigits(string strGuidNotification, string strDigits) {
            this.Invoke("PlayDigits", new object[] {
                        strGuidNotification,
                        strDigits});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPlayDigits(string strGuidNotification, string strDigits, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PlayDigits", new object[] {
                        strGuidNotification,
                        strDigits}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPlayDigits(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/WaitDigits", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WaitDigits(string strGuidNotification, int Timeout, int MaxDigits, string LastDigit) {
            object[] results = this.Invoke("WaitDigits", new object[] {
                        strGuidNotification,
                        Timeout,
                        MaxDigits,
                        LastDigit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWaitDigits(string strGuidNotification, int Timeout, int MaxDigits, string LastDigit, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WaitDigits", new object[] {
                        strGuidNotification,
                        Timeout,
                        MaxDigits,
                        LastDigit}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWaitDigits(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/Record", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Record(string strGuidNotification, int Timeout, string LastDigit, int MaxDigits) {
            object[] results = this.Invoke("Record", new object[] {
                        strGuidNotification,
                        Timeout,
                        LastDigit,
                        MaxDigits});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRecord(string strGuidNotification, int Timeout, string LastDigit, int MaxDigits, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Record", new object[] {
                        strGuidNotification,
                        Timeout,
                        LastDigit,
                        MaxDigits}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/MakeAudioFile", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MakeAudioFile(string strGuidNotification, string strName, string strTextToSpeak) {
            this.Invoke("MakeAudioFile", new object[] {
                        strGuidNotification,
                        strName,
                        strTextToSpeak});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMakeAudioFile(string strGuidNotification, string strName, string strTextToSpeak, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MakeAudioFile", new object[] {
                        strGuidNotification,
                        strName,
                        strTextToSpeak}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndMakeAudioFile(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/GetLastMethodDuration", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLastMethodDuration(string strGuidNotification, string MethodName) {
            object[] results = this.Invoke("GetLastMethodDuration", new object[] {
                        strGuidNotification,
                        MethodName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLastMethodDuration(string strGuidNotification, string MethodName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLastMethodDuration", new object[] {
                        strGuidNotification,
                        MethodName}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetLastMethodDuration(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/SetSearchString", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSearchString(string strGuidNotification, string strValue) {
            this.Invoke("SetSearchString", new object[] {
                        strGuidNotification,
                        strValue});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetSearchString(string strGuidNotification, string strValue, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetSearchString", new object[] {
                        strGuidNotification,
                        strValue}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSetSearchString(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/GetSearchString", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSearchString(string strGuidNotification) {
            object[] results = this.Invoke("GetSearchString", new object[] {
                        strGuidNotification});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSearchString(string strGuidNotification, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSearchString", new object[] {
                        strGuidNotification}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSearchString(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.acrosscommunications.com/Release", RequestNamespace="http://ws.acrosscommunications.com/", ResponseNamespace="http://ws.acrosscommunications.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Release(string strGuidNotification) {
            this.Invoke("Release", new object[] {
                        strGuidNotification});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRelease(string strGuidNotification, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Release", new object[] {
                        strGuidNotification}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndRelease(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
