//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCollection2.Properties {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default {
			get {
				return defaultInstance;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("EN")]
		public string AmazonLocale {
			get {
				return ((string)(this["AmazonLocale"]));
			}
			set {
				this["AmazonLocale"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("DVD")]
		public string AmazonSearchMode {
			get {
				return ((string)(this["AmazonSearchMode"]));
			}
			set {
				this["AmazonSearchMode"] = value;
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
		[global::System.Configuration.DefaultSettingValueAttribute("Data Source=\".\\SQLExpress\";AttachDbFilename=\"|DataDirectory|\\DVDCollectionDatabas" +
			"e.mdf\";Integrated Security=True;User Instance=True")]
		public string Connection1 {
			get {
				return ((string)(this["Connection1"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")]
		public string MovieCollectionAWSv4ZZZ_AmazonServiceSDK_AWSECommerceService {
			get {
				return ((string)(this["MovieCollectionAWSv4ZZZ_AmazonServiceSDK_AWSECommerceService"]));
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0525E2PQ81DD7ZTWTK82")]
		public string AmazonSubscriptionId {
			get {
				return ((string)(this["AmazonSubscriptionId"]));
			}
			set {
				this["AmazonSubscriptionId"] = value;
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlEN {
			get {
				return ((string)(this["AmazonUrlEN"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlUK {
			get {
				return ((string)(this["AmazonUrlUK"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.de/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlDE {
			get {
				return ((string)(this["AmazonUrlDE"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.co.jp/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlJP {
			get {
				return ((string)(this["AmazonUrlJP"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.fr/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlFR {
			get {
				return ((string)(this["AmazonUrlFR"]));
			}
		}

		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.ca/onca/soap?Service=AWSECommerceService")]
		public string AmazonUrlCA {
			get {
				return ((string)(this["AmazonUrlCA"]));
			}
		}
	}
}
